### ISSUE TITLE
box shrink

### ISSUE THREAD

**Issue by mecs13** [mecs13/website_text#8]
+- command, (-)
+- left and right text boxes shrunk but also became devided and distance between them grew
+- Expected entire text to shrinkk but remain proportionate 
+- g chrome
+- mac book pro 11 in

**Comment by tbinetruy** [comment]
Can I get a screenshot please ? Mine don't, see first screenshot.

Cmd- is to zoom out right ? So you'd expect the right panel to shrink and the middle on to grow. Because the left panel is specified by jacques to be fixed size (and so when you zoom out it shrinks). Whereas the middle panel is specified to stretch from a right offset from the menu till the left panel.

![screenshot from 2018-02-14 15-51-52](https://user-images.githubusercontent.com/19936648/36227465-29aacbac-119f-11e8-9998-67015dd5db33.png)

The following screenshot is when extremly zoomed in. Still, no division between the panels.
![screenshot from 2018-02-14 15-55-58](https://user-images.githubusercontent.com/19936648/36227611-95425556-119f-11e8-8e02-fde4ea2c5894.png)

**Comment by tbinetruy** [comment]
Talked to @kylekesses , issue relevant for homepage only.
